CREATE TABLE roles (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE users (
  id int (11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  firstname varchar(20),
  lastname varchar(20),
  email varchar(50) NOT NULL unique,
  password varchar(225) NOT NULL,
  rolesId int(11) UNSIGNED DEFAULT 1,
  FOREIGN KEY (rolesId) REFERENCES roles(id)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;


CREATE TABLE pages (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(20) NOT NULL
  ) ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE projects (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  logourl TEXT NOT NULL,
  url TEXT NOT NULL,
  pagesId INT UNSIGNED,
  FOREIGN KEY (pagesId) REFERENCES pages (id)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE about (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(20) NOT NULL,
  paragraph TEXT NULL,
  logo TEXT,
  pagesId INT UNSIGNED,
  FOREIGN KEY (pagesId) REFERENCES pages (id)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

INSERT INTO roles (name) VALUES ("Membre"),("Admin");